<a href="https://colab.research.google.com/github/justinfmccarty/epwmorph/blob/main/process_modeldata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd

In [ ]:
baselinestart = 1976
baselineend = 2005
pathway = 'ssp245'
futurestart = 2035
futureend = 2065
percentiles = 5,50,95

In [ ]:

percentile_list = list(percentiles)#parse('percentiles').split(',')
percentile_list = list(map(int, percentile_list))

varlist = ['clt', 'huss', 'pr', 'psl', 'rsds', 'tas', 'tasmax', 'tasmin', 'uas', 'vas']

In [ ]:
def calc_model_climatologies(variable, percentile, config):
  hist_file = '/content/historical-{}.csv'.format(var)
  fut_file = '/content/ssp245-{}.csv'.format(var)
  # hist_uas_vas['Datetime'] = pd.to_datetime(hist_uas_vas['date_hist'])

  climatolgies_hist = {}

  hist_init = pd.DataFrame(pd.read_csv(hist_file, usecols=['5','50','95','date']))
  hist_init['date'] = pd.to_datetime(hist_init['date'])
  hist_init = hist_init.set_index('date')
  hist_init = hist_init['{}-01-01'.format(baselinestart) :'{}-12-01'.format(baselineend)]
  hist_init = hist_init.groupby(hist_init.index.month).mean()

  for i in list(range(len(percentile_list))):
    ptile = percentile_list[i]
    climatolgies_hist[ptile] = pd.DataFrame()
    climatolgies_hist[ptile][var] = pd.Series(hist_init[str(ptile)]).rename(var)

In [ ]:
def calc_model_climatologies(variable, percentile):#, config):

  #will need to pull historical start and future start from the config file

  hist_file = '/content/historical-{}.csv'.format(var)
  fut_file = '/content/ssp245-{}.csv'.format(var)

  hist_init = pd.DataFrame(pd.read_csv(hist_file, usecols=[percentile,'date']))
  hist_init['date'] = pd.to_datetime(hist_init['date'])
  hist_init = hist_init.set_index('date')
  hist_init = hist_init['{}-01-01'.format(baselinestart) :'{}-12-01'.format(baselineend)]
  hist_init = hist_init.groupby(hist_init.index.month).mean()

  var_init = pd.DataFrame(pd.read_csv(fut_file, usecols=[percentile,'date']))
  var_init['date'] = pd.to_datetime(var_init['date'])
  var_init = var_init.set_index('date')
  var_init = var_init['{}-01-01'.format(futurestart) :'{}-12-01'.format(futureend)]
  var_init = var_init.groupby(var_init.index.month).mean()

  return hist_init, var_init

In [ ]:
a, b = calc_model_climatologies('clt', '95')
# fut_file = '/content/ssp245-{}.csv'.format(var)
# pd.DataFrame(pd.read_csv(fut_file, usecols=['95','date']))

100*((b - a) / a)

### Read and Write EPW

In [ ]:
!pip install git+https://github.com/building-energy/epw

In [26]:
from epw import epw

In [40]:
a = epw()
a.read('/content/CAN_BC_Vancouver.Intl.AP.718920_CWEC2016.epw')
a.dataframe['Year'] = 2050
a.dataframe

      Year  Month  ...  Liquid Precipitation Depth  Liquid Precipitation Quantity
0     2050      1  ...                         0.0                            0.0
1     2050      1  ...                         0.0                            0.0
2     2050      1  ...                         0.0                            0.0
3     2050      1  ...                         0.0                            0.0
4     2050      1  ...                         0.0                            0.0
...    ...    ...  ...                         ...                            ...
8755  2050     12  ...                         0.0                            0.0
8756  2050     12  ...                         0.0                            0.0
8757  2050     12  ...                         0.0                            0.0
8758  2050     12  ...                         0.0                            0.0
8759  2050     12  ...                         0.0                            0.0

[8760 rows x 35 columns]

In [62]:
def out_epw(fut_df, year, outputpath):
  base_epw = '/content/CAN_BC_Vancouver.Intl.AP.718920_CWEC2016.epw'
  a = epw()
  a.read(base_epw)
  new_epw = a.dataframe
  new_epw['Year'] = year
  # epw['Dry Bulb Temperature'] = fut_df['drybulb_C']
  # epw['Relative Humidity'] = fut_df['relhum_percent']
  # epw['Dew Point Temperature'] = fut_df['dewpoint_C']
  # epw['Atmospheric Station Pressure'] = fut_df['drybulb_C']
  # epw['Global Horizontal Radiation'] = fut_df['atmost_Pa']
  # epw['Direct Normal Radiation'] = fut_df['dirnorrad_Whm2']
  # epw['Diffuse Horizontal Radiation'] = fut_df['difhorrad_Whm2']
  # epw['Wind Speed'] = fut_df['windspd_ms']
  # epw['Total Sky Cover'] = fut_df['totskycvr_tenths']
  # epw['Opaque Sky Cover (used if Horizontal IR Intensity missing)'] = fut_df['opaqskycvr_tenths']
  # # epw['Horizontal Infrared Radiation Intensity'] = fut_df['horirsky_Whm2']
  # # epw['Precipitable Water'] = fut_df['precip_wtr_mm']
  # epw['Extraterrestrial Horizontal Radiation'] = fut_df['exthorrad_Whm2']
  # epw['Extraterrestrial Direct Normal Radiation'] = fut_df['extdirrad_Whm2']
  # epw['Global Horizontal Illuminance'] = fut_df['glohorillum_lux']
  # epw['Direct Normal Illuminance'] = fut_df['dirnorillum_lux']
  # epw['Diffuse Horizontal Illuminance'] = fut_df['difhorillum_lux']
  # epw['Zenith Luminance'] = fut_df['zenlum_lux']
  a.write(outputpath)
  return print('Done')

In [63]:
df = pd.DataFrame()

out_epw(df, 2075, '/content/out3.epw')

Done

In [64]:
a = epw()
a.read('/content/out3.epw')
a.dataframe

      Year  Month  ...  Liquid Precipitation Depth  Liquid Precipitation Quantity
0     2075      1  ...                         0.0                            0.0
1     2075      1  ...                         0.0                            0.0
2     2075      1  ...                         0.0                            0.0
3     2075      1  ...                         0.0                            0.0
4     2075      1  ...                         0.0                            0.0
...    ...    ...  ...                         ...                            ...
8755  2075     12  ...                         0.0                            0.0
8756  2075     12  ...                         0.0                            0.0
8757  2075     12  ...                         0.0                            0.0
8758  2075     12  ...                         0.0                            0.0
8759  2075     12  ...                         0.0                            0.0

[8760 rows x 35 columns]